softformance_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.home, name="home"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path('<str:filter_by>/', views.home, name="filter"),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Ownable(models.Model):
    user = models.ForeignKey('auth.User', verbose_name="Author",
                             related_name="%(class)ss",
                             on_delete=models.PROTECT)

    class Meta:
        abstract = True


class RegisteredUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    tracking = models.ManyToManyField('self',
                                      related_name='tracked_by',
                                      blank=True, symmetrical=False)

    def __str__(self):
        return self.user.username


class FeedItem(Ownable):
    content = models.CharField("Content", max_length=1000,
                               blank=True, null=True)

    def __str__(self):
        return self.content[:50]

users/views.py
import django.utils.functional
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .models import RegisteredUser, FeedItem


class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


def home(request, filter_by='all_posts') -> django.shortcuts.render:
    template_name = "users/index.html"
    user = request.user
    match filter_by:
        case 'my_posts':
            feed_items = FeedItem.objects.filter(user=user)
        case 'peoples_posts':
            feed_items = get_peoples_posts(user)
        case _:
            feed_items = FeedItem.objects.all()
    context = {
        'feed_items': feed_items,
    }
    if user.is_authenticated and not RegisteredUser.objects.filter(user=user):
        RegisteredUser(user=user).save()
    return render(request, template_name, context)


def get_peoples_posts(user: django.utils.functional.SimpleLazyObject) -> list:
    users_followed = RegisteredUser.objects.get(user=user).tracking.all()
    feed_items = []
    for user_followed in users_followed:
        feed_items.extend(FeedItem.objects.filter(user=user_followed.user))
    return feed_items

users/templates/users/index.html
<html lang="en">
<head>
    <style>
        body {
            color: darkblue;
            text-align: left;
        }

        a {
            color: darkred;
        }

    </style>
    <title>Home</title>
</head>
<body>

<h1>Hello, {{ user.username|default:'Guest' }}</h1>

{% if not user.username %}
    <h3>Login: <a>user1</a> ; Password: <a>qwerty5683</a></h3>
    <h3>Login: <a>user2</a> ; Password: <a>qwerty5683</a></h3>
    <h3>Login: <a>user3</a> ; Password: <a>qwerty5683</a></h3>
{% endif %}

<h2> Welcome to the site</h2>
<div>
    {% if user.is_authenticated %}

        <a href="{% url 'logout' %}">Logout</a>
        <hr>
        <button onclick="document.location='{% url 'users:filter' 'all_posts' %}'">All posts</button>
        <button onclick="document.location='{% url 'users:filter' 'my_posts' %}'">My posts</button>
        <button onclick="document.location='{% url 'users:filter' 'peoples_posts' %}'">Posts from people I follow.
        </button>

    {% else %}
        <a href="{% url 'users:signup' %}">Sign Up</a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'login' %}">Login</a>
        <hr>
        <button onclick="document.location='{% url 'users:filter' 'all_posts' %}'">All posts</button>
        <button onclick="document.location='{% url 'login' %}'">My posts</button>
        <button onclick="document.location='{% url 'login' %}'">Posts from people I follow.</button>
    {% endif %}
</div>
<hr>

<ul>
    {% for item in feed_items %}
        <li>{{ item.content }}</li>
        <hr>
    {% endfor %}
</ul>

</body>
</html>